# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - Uniswap/v3-core@1.0.0
compiler:
  solc:
    version: 0.8.13
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
networks:
  default: development
  goerli:
    chainid: 5
    stargate:
      # Will be deployed soon
      router:
      chainid: 10121
      poolid:
        usdc: 1
        weth: 13
    wormhole:
      chainid: 2
      token_bridge: "0xF890982f9310df57d00f659cf4fd87e65adEd8d7"
    oracle:
      eth:
        chainid: 2
        address: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    token:
      usdc:
        address: "0x2f3A40A3db8a7e3D09B0adfEfbCe4f6F81927557"
        decimal: 6
      weth:
        address: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
        decimal: 18
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: UniswapV2
        router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        token_list: ""
  bsc-test:
    chainid: 97
    wormhole:
      chainid: 4
      token_bridge: "0x9dcF9D205C9De35334D646BeE44b2D2859712A09"
      actual_reserve: 1.1
      estimate_reserve: 1.2
      gas:
        avax:
          dst_chainid: 6
          base_gas: 21000
          per_byte_gas: 68
        polygon:
          dst_chainid: 5
          base_gas: 21000
          per_byte_gas: 68
        eth:
          dst_chainid: 2
          base_gas: 21000
          per_byte_gas: 68
    oracle:
      bsc:
        chainid: 4
        address: "0x2514895c72f50D8bd4B4F9b1110F0D6bD2c97526"
      eth:
        chainid: 2
        address: "0x143db3CEEfbdfe5631aDD3E50f7614B6ba708BA7"
      matic:
        chainid: 5
        address: "0x957Eb0316f02ba4a9De3D308742eefd44a3c1719"
    stargate:
      router: "0xbB0f1be1E9CE9cB27EA5b0c3a85B7cc3381d8176"
      chainid: 10102
      poolid:
        usdt: 2
    token:
      usdt:
        address: "0xF49E250aEB5abDf660d643583AdFd0be41464EfD"
        decimal: 18
      weth:
        address: "0xae13d989dac2f0debff460ac112a837c89baa7cd"
        decimal: 18
      wavax:
        address: "0x6cE9E2c8b59bbcf65dA375D3d8AB503c8524caf7"
        decimal: 18
      wusdc:
        address: "0x71b7E25BE7879E042E55FBabD4037De116ae07e0"
        decimal: 6
      wbtc:
        address: "0x0ecacbE08B4E2AA71B8f71ECe35A7EbF815607E8"
        decimal: 18
      aave:
        address: "0x662046742e926D1Ffa5Ffce198bB025b2df0bDEe"
        decimal: 18
      dai:
        address: "0x6B41b85629Bc293F5e00A2EEfB50D0B1Bc35b367"
        decimal: 18
      uni:
        address: "0xb3841879399923B35101FB033aa936199E5255E1"
        decimal: 18
    swap:
      IUniswapV2Router02:
        name: UniswapV2
        router: "0xD99D1c33F9fC3444f8101754aBC46c52416550D1"
        token_list: ""
  avax-test:
    chainid: 43113
    wormhole:
      chainid: 6
      token_bridge: "0x61E44E506Ca5659E6c0bba9b678586fA2d729756"
      actual_reserve: 1.1
      estimate_reserve: 1.2
      gas:
        bsc:
          dst_chainid: 4
          base_gas: 21000
          per_byte_gas: 68
        polygon:
          dst_chainid: 5
          base_gas: 21000
          per_byte_gas: 68
        eth:
          dst_chainid: 2
          base_gas: 21000
          per_byte_gas: 68
    oracle:
      avax:
        chainid: 6
        address: "0x5498BB86BC934c8D34FDA08E81D444153d0D06aD"
      matic:
        chainid: 5
        address: "0xB0924e98CAFC880ed81F6A4cA63FD61006D1f8A0"
    stargate:
      router: "0x13093E05Eb890dfA6DacecBdE51d24DabAb2Faa1"
      chainid: 10106
      poolid:
        usdc: 1
    token:
      usdc:
        address: "0x4A0D1092E9df255cf95D72834Ea9255132782318"
        decimal: 6
      weth:
        # DexLot used weth
        address: "0x9B5828d46A43176F07656e162cCbDc787624468c"
        # Hurricaneswap used weth "0xd00ae08403B9bbb9124bB305C09058E32C39A48c"
        decimal: 18
      wbnb:
        address: "0x10F1053bF2884b28ee0Bd7a2dDBa237Af3511d29"
        decimal: 18
      wusdt:
        address: "0x8337e5eF98af25012e1B39CD996772143f6c5fDf"
        decimal: 18
      wbtc:
        address: "0x93056503b159fa416Ed5e8eF3907e2F01CAD1eDD"
        decimal: 18
      aave:
        address: "0x2c0C13029742a116D83e3581B85438Af821B8053"
        decimal: 18
      dai:
        address: "0xB09CC68675349e13cc76921154940C7A4b19cf60"
        decimal: 18
      uni:
        address: "0x215B7e1dFC3A1757016cF8A531cF929F2b3FC4B1"
        decimal: 18
    swap:
      IUniswapV2Router02AVAX:
        name: DexLotV2
        router: "0x6D481b9F59b22B6eB097b986fC06E438d585c039"
        token_list: ""
  #      IUniswapV2Router02AVAX:
  #        name: HurricaneswapV2
  #        router: "0x7E3411B04766089cFaa52DB688855356A12f05D1"
  #        token_list: ""
  polygon-test:
    chainid: 80001
    wormhole:
      chainid: 5
      token_bridge: "0x377D55a7928c046E18eEbb61977e714d2a76472a"
      actual_reserve: 1.1
      estimate_reserve: 1.2
      gas:
        avax:
          dst_chainid: 6
          base_gas: 21000
          per_byte_gas: 68
        bsc:
          dst_chainid: 4
          base_gas: 21000
          per_byte_gas: 68
        eth:
          dst_chainid: 2
          base_gas: 21000
          per_byte_gas: 68
    oracle:
      matic:
        chainid: 5
        address: "0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada"
    stargate:
      router: "0x817436a076060D158204d955E5403b6Ed0A5fac0"
      chainid: 10109
      poolid:
        usdc: 1
    token:
      usdc:
        address: "0x742DfA5Aa70a8212857966D491D67B09Ce7D6ec7"
        decimal: 6
      weth:
        address: "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889"
        decimal: 18
    swap:
      IUniswapV2Router02AVAX:
        name: UniswapV2
        router: "0x8954AfA98594b838bda56FE4C12a09D7739D179b"
        token_list: ""
  arbitrum-test:
    chainid: 421611
    stargate:
      router: "0x6701D9802aDF674E524053bd44AA83ef253efc41"
      chainid: 10110
      poolid:
        usdc: 1
        weth: 13
    token:
      usdc:
        address: "0x1EA8Fb2F671620767f41559b663b86B1365BBc3d"
        decimal: 6
      weth:
        address: "0xB47e6A5f8b33b3F17603C83a0535A9dcD7E32681"
        decimal: 18
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: UniswapV2
        router: "0xb5a35165047fed7440D3a75909c0949bf1943696"
        token_list: ""
  optimism-test:
    chainid: 69
    stargate:
      router: "0xCC68641528B948642bDE1729805d6cf1DECB0B00"
      chainid: 10111
      poolid:
        usdc: 1
        weth: 13
    token:
      usdc:
        address: "0x567f39d9e6d02078F357658f498F80eF087059aa"
        decimal: 6
      weth:
        address: "0x4200000000000000000000000000000000000006"
        decimal: 18
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
  ftm-test:
    chainid: 4002
    stargate:
      router: "0xa73b0a56B29aD790595763e71505FCa2c1abb77f"
      chainid: 10112
      poolid:
        usdc: 1
    token:
      usdc:
        address: "0x076488D244A73DA4Fa843f5A8Cd91F655CA81a1e"
        decimal: 6
      weth:
        address: "0x9B5828d46A43176F07656e162cCbDc787624468c"
        decimal: 18
    swap:
      IUniswapV2Router02:
        name: UniswapV2
        router: "0x6D481b9F59b22B6eB097b986fC06E438d585c039"
        token_list: ""
  mainnet:
    chainid: 1
    stargate:
      router: "0x8731d54E9D02c286767d56ac03e8037C07e01e98"
      chainid: 101
      poolid:
        usdc: 1
        usdt: 2
        usdd: 11
        weth: 13
    token:
      weth:
        address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        decimal: 18
      usdc:
        address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
        decimal: 6
      usdt:
        address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        decimal: 6
      usdd:
        address: "0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6"
        decimal: 18
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: UniswapV2
        router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        token_list: "https://tokens.uniswap.org/"
  bsc-main:
    chainid: 56
    stargate:
      router: "0x4a364f8c717cAAD9A442737Eb7b8A55cc6cf18D8"
      chainid: 102
      poolid:
        usdt: 2
    token:
      usdt:
        address: "0x55d398326f99059fF775485246999027B3197955"
        decimal: 18
      busd:
        address: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
        decimal: 18
      usdd:
        address: "0xd17479997F34dd9156Deef8F95A52D81D265be9c"
        decimal: 18
      weth:
        address: "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"
        decimal: 18
    swap:
      IUniswapV2Router02:
        name: PancakeSwapV2
        router: "0x10ED43C718714eb63d5aA57B78B54704E256024E"
        token_list: "https://tokens.pancakeswap.finance/pancakeswap-top-100.json"
  avax-main:
    chainid: 43114
    stargate:
      router: "0x45A01E4e04F14f7A4a6702c74187c5F6222033cd"
      chainid: 106
      poolid:
        usdc: 1
        usdt: 2
    token:
      weth:
        address: "0xb31f66aa3c1e785363f0875a1b74e27b85fd66c7"
        decimal: 18
      usdc:
        address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
        decimal: 6
      usdt:
        address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"
        decimal: 6
    swap:
      IUniswapV2Router02AVAX:
        name: PangolinV2
        router: "0xE54Ca86531e17Ef3616d22Ca28b0D458b6C89106"
        token_list: "https://raw.githubusercontent.com/pangolindex/tokenlists/main/pangolin.swap_tokenlist.json"
  polygon-main:
    chainid: 137
    stargate:
      router: "0x45A01E4e04F14f7A4a6702c74187c5F6222033cd"
      chainid: 109
      poolid:
        usdc: 1
        usdt: 2
    token:
      weth:
        address: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"
        decimal: 18
      usdc:
        address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
        decimal: 6
      usdt:
        address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
        decimal: 6
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: QuickswapV2
        router: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
        token_list: "https://unpkg.com/quickswap-default-token-list@1.2.38/build/quickswap-default.swap_tokenlist.json"
  arbitrum-main:
    chainid: 42161
    stargate:
      router: "0x53Bf833A5d6c4ddA888F69c22C88C9f356a41614"
      chainid: 110
      poolid:
        usdc: 1
        weth: 13
    token:
      usdt:
        address: "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"
        decimal: 6
      usdc:
        address: "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8"
        decimal: 6
      weth:
        address: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1"
        decimal: 18
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: ""
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: SushiswapV2
        router: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
        token_list: ""
  optimism-main:
    chainid: 10
    stargate:
      router: "0xB0D502E938ed5f4df2E681fE6E419ff29631d62b"
      chainid: 111
      poolid:
        usdc: 1
        weth: 13
    token:
      weth:
        address: "0x4200000000000000000000000000000000000006"
        decimal: 18
      usdc:
        address: "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"
        decimal: 6
    swap:
      ISwapRouter:
        name: UniswapV3
        router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
        token_list: "https://static.optimism.io/optimism.swap_tokenlist.json"
        quoter: "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"
      IUniswapV2Router02:
        name: ZipSwapV2
        router: "0xE6Df0BB08e5A97b40B21950a0A51b94c4DbA0Ff6"
        token_list: ""
  ftm-main:
    chainid: 250
    stargate:
      router: "0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6"
      chainid: 112
      poolid:
        usdc: 1
    swap:
      IUniswapV2Router02:
        name: SpookyswapV2
        router: "0xF491e7B69E4244ad4002BC14e878a34207E38c29"
        token_list: "https://docs.spooky.fi/Resources/ftm-token-addresses"
#      IUniswapV2Router02:
#        name: Spiritswap
#        router: "0x16327E3FbDaCA3bcF7E38F5Af2599D2DDc33aE52"
#        token_list: "https://docs.spooky.fi/Resources/ftm-token-addresses"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
