[features]
seeds = false
skip-lint = false

[programs.devnet]
omniswap = "9YYGvVLZJ9XmKM2A1RNv1Dx3oUnHWgtXWt8V3HU5MtXU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/chain/.config/solana/id.json"
