[features]
seeds = false
skip-lint = false
[programs.devnet]
omniswap = "5DncnqicaHDZTMfkcfzKaYP5XzD5D9jg3PGNTT5J1Qg7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/chain/.config/solana/id.json"
